CREATE TABLE `up6_files` (
  `f_id` int(11) NOT NULL auto_increment,
  `f_pid` int(11) default '0',
  `f_pidRoot` int(11) default '0',
  `f_fdTask` tinyint(1) default '0',
  `f_fdID` int(11) default '0',
  `f_fdChild` tinyint(1) default '0',
  `f_uid` int(11) default '0',
  `f_nameLoc` varchar(255) default '',
  `f_nameSvr` varchar(255) default '',
  `f_pathLoc` varchar(255) default '',
  `f_pathSvr` varchar(255) default '',
  `f_pathRel` varchar(255) default '',
  `f_md5` varchar(40) default '',
  `f_lenLoc` bigint(19) default '0',
  `f_sizeLoc` varchar(10) default '0',
  `f_pos` bigint(19) default '0',
  `f_lenSvr` bigint(19) default '0',
  `f_perSvr` varchar(6) default '0%',
  `f_complete` tinyint(1) default '0',
  `f_time` timestamp NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `f_deleted` tinyint(1) default '0',
  PRIMARY KEY  (`f_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
